# Generated by Django 3.2.4 on 2021-10-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debugtalks',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='内置函数名', max_length=255, unique=True, verbose_name='内置函数名')),
                ('debugtalk', models.TextField(default='#debugtalk.py', help_text='debugtalk.py文件', verbose_name='debugtalk.py文件')),
                ('project', models.OneToOneField(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '内置函数表',
                'verbose_name_plural': '内置函数表',
                'db_table': 'debugtalks_tb',
            },
        ),
    ]
