# Generated by Django 3.2.4 on 2021-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalks',
            name='name',
            field=models.CharField(default='debugtalk.py', help_text='内置函数名', max_length=255, verbose_name='内置函数名'),
        ),
    ]
